### ISSUE TITLE
standard_init_linux.go:190: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by pilip87** [weweave/landroid-bridge#42]
Just installed on raspberry pi b3+ using docker. When I start the container I get 

standard_init_linux.go:190: exec user process caused "exec format error"

And if I access the webpage I get 404 not found

Help?
Thank you
Filippo

**Comment by mhaack** [comment]
Is the RPI docker image actually still maintained? https://hub.docker.com/r/weweave/landroid-bridge/tags is not updated since months?

**Comment by derandiunddasbo** [comment]
> When I start the container I get standard_init_linux.go:190: exec user process caused "exec format error"

You have to pull and run the image explicitly with the arm32v7 tag to actually use the arm image instead of the x86 version:

```
docker pull weweave/landroid-bridge:arm32v7

[...]

docker run -p 3000:3000 weweave/landroid-bridge:arm32v7
```

But as @mhaack already mentioned: the arm image was last udated 11 month ago and lacks the fix for the API change. Thus, ATM you get rid of the `exec format error`, which is replaced by the `Unhandled exception: SyntaxError: Unexpected token N in JSON at position 0` error. ;-)

So, could someone please update the ARM image?

**Comment by pilip87** [comment]
Thanks I've created new issue for that. This could be considered closed
